version: '2.1'

services:
  client:
    image: tf-client-go
    build: .
    ports:
      - 1323:1323
  model-server:
    image: daxiang6506/tensorflow-serving:1.8.0
    volumes:
      - /Users/xuc/docker/Tensorflow-Serving:/bitnami/model-data